### ISSUE TITLE
undetermined naming. Looking for ...

### ISSUE THREAD

**Issue by odlan** [bateman/corsaronero-cp-provider#10]
Prima di tutto ciao e grazie per il tuo contributo
Ho installato il plugin su Couchpotato V2 e sembra funzionare.
Il problema che riscontro, come già segnalato anche da te ed altri, sembra essere l' anno che spesso o sempre non viene indicato nelle release presenti su CorsaroNero.
Vorrei suggerirti la possibilità, come documentato qui https://couchpota.to/forum/viewtopic.php?f=18&t=4423&hilit=year&start=20#p22295, di aggiungere qualche riga di codeice nel file __init__.py e main.py che diano la possibilità con un check box nelle impostazioni del provider di escludere l' anno dalla stringa di ricerca nel caso non ritorni alcun risultato per il film desiderato.
Purtoppo non ho particolari abilità per fare da solo se non quelle di cercare in giro per la rete casi simili. Grazie ancora per il tuo lavoro
Ho aperto una discussione sul forum di Couchpotato e più esattamente qui  https://couchpota.to/forum/viewtopic.php?f=5&t=4750#p22809 dove mi si consiglia di rivolgermi a te.
Di seguito i log
   
 ### Steps to reproduce:
    1. I'm looking for films in italian language only, nothing is snatched. In required words I have set :"ita, Italian, italiano". No ignored words. Some preferred words
    2. I see in logs that when I'm looking for "l'Odio" core.media.movie.searcher find the film but something doesn't match (Wrong undetermined naming)

    ### Information:
    Movie(s) I have this with: L' Odio
    Quality of the movie being searched: best
    Providers I use: Torrentz, Yify, TNT Village, The Pirate Bay, CorsaroNero, HDBits, KickAssTorrents
    Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 0288cc88 (2014-12-22 22:02:05)
    Running on: Synology Diskstation 1511+

    ### Logs:
    ```
    12-25 14:00:10 INFO [ corsaronero] Hit right category: DVDrip is a movie, keep going.
    12-25 14:00:10 DEBUG [hpotato.core.plugins.base] Waiting for CorsaroNero, 1 seconds
    12-25 14:00:10 DEBUG [ tntvillage] Searching for la haine (imdb: 0113247) (720p) on http://forum.tntvillage.scambioetico.org/index.php
    12-25 14:00:10 DEBUG [hpotato.core.plugins.base] Getting cache italiantitle.tt0113247
    12-25 14:00:10 DEBUG [ tntvillage] Title after searching for the italian one: L'odio
    12-25 14:00:10 DEBUG [o.core.notifications.core] Getting messages with id: 0a71c492-c59a-46a4-8795-c6fe3fd6f7c1
    12-25 14:00:10 DEBUG [o.core.notifications.core] Returning for 0a71c492-c59a-46a4-8795-c6fe3fd6f7c1 0 messages
    12-25 14:00:10 DEBUG [hpotato.core.plugins.base] Setting cache e7d6dee4dffc9ab9bfaa6bfe0538672b
    12-25 14:00:11 INFO [hpotato.core.plugins.base] Opening url: get http://ilcorsaronero.info/tor/101264/L_ ... ub_Orgazmo, data: []
    12-25 14:00:11 DEBUG [hpotato.core.plugins.base] Setting cache c99c4a9365c1677477d4af540eb427f8
    12-25 14:00:11 DEBUG [tato.core.plugins.quality] Found 1080p via release size: 4000.0 MB < 5898.24 MB < 20000.0 MB
    12-25 14:00:11 DEBUG [tato.core.plugins.quality] Found 720p via release size: 3000.0 MB < 5898.24 MB < 10000.0 MB
    12-25 14:00:11 DEBUG [tato.core.plugins.quality] Found brrip via release size: 700.0 MB < 5898.24 MB < 7000.0 MB
    12-25 14:00:11 DEBUG [tato.core.plugins.quality] Found dvdr via release size: 3000.0 MB < 5898.24 MB < 10000.0 MB
    12-25 14:00:11 DEBUG [hpotato.core.plugins.base] Setting cache ['L_Odio_La_Haine_HDmux_720p_x264_ITA_Ac3_FRE_Dts_Multisub_Orgazmo']
    12-25 14:00:11 DEBUG [hpotato.core.plugins.base] Getting cache ['L_Odio_La_Haine_HDmux_720p_x264_ITA_Ac3_FRE_Dts_Multisub_Orgazmo']
    12-25 14:00:11 INFO [core.media.movie.searcher] Wrong: L_Odio_La_Haine_HDmux_720p_x264_ITA_Ac3_FRE_Dts_Multisub_Orgazmo, undetermined naming. Looking for 'La Haine (1995)'
    12-25 14:00:11 DEBUG [ corsaronero] New result {'seeders': 25, 'name': 'L_Odio_La_Haine_HDmux_720p_x264_ITA_Ac3_FRE_Dts_Multisub_Orgazmo', 'url': 'magnet:?xt=urn:btih:a7bd0dde5802728d25b05e06fba53a756afde3e9&dn=L.Odio.La.Haine.HDmux.720p.x264.ITA.Ac3.FRE.Dts.Multisub.Orgazmo&tr=http%3A%2F%2Ftracker.tntvillage.scambioetico.org%3A2710%2Fannounce', 'age': 24, 'leechers': 31, 'score': 0, 'detail_url': 'http://ilcorsaronero.info/tor/101264/L_Odio_La_Haine_HDmux_720p_x264_ITA_Ac3_FRE_Dts_Multisub_Orgazmo', 'id': '101264', 'size': 5898.2399999999998}
    12-25 14:00:11 INFO [ corsaronero] Hit right category: DVDrip is a movie, keep going.

**Comment by bateman** [comment]
Ciao,
grazie per la tua domanda e l'interessa. Ti chiedo scusa per la risposta in ritardo. Al momento per lavoro non ho molto tempo da dedicare ad altri progetti. Per lo stesso motivo, anche se la modifica che richiedi non è complessa -- almeno credo -- non posso dirti quando saro' in grado di lavorarci. Ne prendo nota tra gli issue e appena possibile, vedro' di lavorarci.
grazie ancora,
fabio

**Comment by neothematrix** [comment]
ciao Fabio,
ho iniziato a guardarci io tempo fa, la modifica non è così banale come sembra purtroppo, ad ogni modo, cerco di fare il possibile anche se ignorare l'anno vorrà dire che sarà più facile incorrere in errate release scaricate.

**Comment by neothematrix** [comment]
(si imparano sempre nuove cose, non sapevo si potessero assegnare gli issue, è proprio serio questo github :-) )

**Comment by bateman** [comment]
grazie. Stai lavorando sul tuo fork? così posso seguire i tuoi progressi
ed, eventualmente, incorporare le modifiche per chiudere l'issue.
grazie ancora e buon lavoro.

-- Fabio

**Comment by neothematrix** [comment]
per ora sul fork locale, non committato sul mio fork, ma lo farò senz'altro.

**Comment by neothematrix** [comment]
ciao, ho appena "mergiato" il fix per che aggiunge l'opzione per ignorare l'anno nella ricerca, mi fate avere qualche riscontro? io ho già visto che un paio di film che avevo in coda me li ha scaricati (e prima non trovava nulla). L'opzione va abilitata nelle opzioni del "searcher" ilcorsaronero nella configurazione di couchpotato, l'unico problema è che ignorando l'anno, potrebbero venire scaricati film che non sono quelli che ci aspettiamo, ma forse per noi italiani, è un compromesso accettabile :-)

**Comment by neothematrix** [comment]
un consiglio, per cercare i titoli in italiano, questa modifica banalissima che ho postato anche sulle feature request di CP, si tratta di aggiungere due righe in un file:

https://github.com/RuudBurger/CouchPotatoServer/issues/1300#issuecomment-70510787

**Comment by bateman** [comment]
funziona per me, grazie ;-)

**Comment by bateman** [comment]
interessante, gabriele.
per "very slow" che intendi? puoi quantificare??

**Comment by neothematrix** [comment]
allora la prima modifica che propongo, che va bene solo per una lingua è questa:
```
diff --git a/couchpotato/core/media/movie/providers/info/themoviedb.py b/couchpotato/core/media/movie/providers/info/themoviedb.py
index 713d505..5d25cee 100644
--- a/couchpotato/core/media/movie/providers/info/themoviedb.py
+++ b/couchpotato/core/media/movie/providers/info/themoviedb.py
@@ -47,6 +47,7 @@ class TheMovieDb(MovieProvider):
             raw = self.request('search/movie', {
                 'query': name_year.get('name', q),
                 'year': name_year.get('year'),
+                'language': 'it',
                 'search_type': 'ngram' if limit > 1 else 'phrase'
             }, return_key = 'results')
         except:
@@ -90,6 +91,7 @@ class TheMovieDb(MovieProvider):

         # Do request, append other items
         movie = self.request('movie/%s' % movie.get('id'), {
+            'language': 'it',
             'append_to_response': 'alternative_titles' + (',images,casts' if extended else '')
         })
         if not movie:
```
e non comporta assolutamente nessun rallentamento, semplicemente forza la query alle api di themoviedb a ritornare, oltre al titolo originale, anche il titolo in italiano.

La seconda modifica invece permette di chiedere a themoviedb TUTTE le traduzioni del titolo in tutte le lingue disponibili, purtroppo per farlo è obbligatorio fare tante chiamate HTTP quante sono le traduzioni presenti per ogni singolo film, e considerato che couchpotato ha un meccanismo per evitare di floodare themoviedb, si riesce a fare una chiamata al secondo, il che vuol dire che se un film ha 10 traduzioni, sono 10 secondi, considera che questo meccanismo entra in funzione anche quando fai la ricerca con le suggestion per aggiungere un nuovo film a couchpotato, tradotto: è praticamente inutilizzabile, meglio la prima soluzione.
