### ISSUE TITLE
Non riesco a trovare nulla

### ISSUE THREAD

**Issue by ikaroweb** [bateman/corsaronero-cp-provider#13]
Salve ragazzi!
Ho provato ad usare lo script, ma su il corsaro non riesco a trovare nulla, mentre la versione per tntvillage funziona bene.
Sbaglio io a cercare oppure qualcosa non va nello script ?

Grazie Ika ;)

**Comment by neothematrix** [comment]
ciao!
io lo uso e funziona correttamente, ci possono essere moltissimi motivi per cui non trovi nulla su ilcorsaronero, primo tra tutti l'assenza dell'anno nel titolo del film. Così senza log o altre informazioni dettagliate pero' nessuno puo darti una mano, incolla magari un log di una ricerca non funzionante.

**Comment by ikaroweb** [comment]
Ciao!
Prova a dirmi tu un titolo cosi faccio una ricerca e vediamo se sbaglio io qualcosa ? 
Grazie

**Comment by neothematrix** [comment]
boh Gravity per esempio

**Comment by ikaroweb** [comment]
Ok provo e ti dico

**Comment by ikaroweb** [comment]
Io l'ho configurato cosi:

![schermata 2016-03-03 alle 21 02 22](https://cloud.githubusercontent.com/assets/3315360/13507515/2f711cb0-e183-11e5-8079-f5e44456db1d.png)

Aggiunto Gravity ma non mi sembra trovi nulla.

![schermata 2016-03-03 alle 21 03 19](https://cloud.githubusercontent.com/assets/3315360/13507536/475604b2-e183-11e5-9e51-0ea503bf6936.png)

Che log ti occorre cosi lo incollo ?

Grazie

**Comment by neothematrix** [comment]
CouchPotato.log dovrebbe essere nella cartella "Log" di CouchPotato, fai una cosa, assicurati che sia in modalità debug il log nelle opzioni di couchpotato, ferma couchpotato, elimina l'eventuale log esistente e fallo ripartire, poi ripeti la ricerca del film e manda il log, possibilmente su pastebin.com per poi incollare il link qui

**Comment by ikaroweb** [comment]
Ora sembra che abbia trovato la versione 1080p però su transmission non vedo nulla.

![schermata 2016-03-03 alle 21 08 24](https://cloud.githubusercontent.com/assets/3315360/13507681/022416b2-e184-11e5-863d-851e49ceffc0.png)

**Comment by neothematrix** [comment]
no log, no party

**Comment by ikaroweb** [comment]
Ora mi dice questo:

http://pastebin.com/hpxetmYp

Provo a cancellare il file torrent e riprovo ?

**Comment by neothematrix** [comment]
eh si

**Comment by ikaroweb** [comment]
Allora su debug ora non mostra nulla se vuoi ti incollo gli altri log.

**Comment by neothematrix** [comment]
non so che dirti, prova con altri film, il fatto che questo l'abbia trovato e preso dal corsaronero significa che è tutto ok col plugin.

**Comment by ikaroweb** [comment]
Questo è quello che ho nel log.

http://pastebin.com/jjaPNBWU

Provo con altro film vediamo.

**Comment by ikaroweb** [comment]
Ho riavviato il servizio e ora ci sono i log anche nel debug.

**Comment by ikaroweb** [comment]
Archivio zip con log 
[Archivio.zip](https://github.com/bateman/corsaronero-cp-provider/files/157684/Archivio.zip)

**Comment by ikaroweb** [comment]
Ma il download dovrebbe partire in automatico oppure devo selezionare io cosa scaricare ?

**Comment by neothematrix** [comment]
in teoria dovrebbe partire scegliendo in automatico uno di quei risultati, per qualche motivo non l'ha fatto ma puoi scegliere tu uno di quelli cliccando sulla seconda icona alla fine della riga

**Comment by ikaroweb** [comment]
Si ho già provato a cliccare sull'icona di download ma non scarica nulla.

**Comment by neothematrix** [comment]
Potrebbe essere perché hai impostato transmission per scaricare usando il "blackhole"? Ilcorsaro ha dei link "magnet" quindi devi impostare couchpotato per chiamare direttamente transmission, quindi non come blackhole ma con la configurazione specifica del Downloader transmission su couchpotato

**Comment by ikaroweb** [comment]
Ok disattivato "blackhole", vediamo se va.

**Comment by ikaroweb** [comment]
Perfetto ora è partito grazie! :100:
