### ISSUE TITLE
Non funziona più

### ISSUE THREAD

**Issue by vivi202** [bateman/corsaronero-cp-provider#16]

**Comment by neothematrix** [comment]
ciao, qualche info in più? che errore hai? non funziona piu la ricerca o il download? che prove stai facendo?
grazie

**Comment by neothematrix** [comment]
mmm vedo che itorrents.org ha attivato Cloudflare, un sistema anti bot per verificare che chi sta scaricando non sia un bot. Generalmente questi provvedimenti sono temporanei, se puoi riprovare più tardi si dovrebbe sbloccare, altrimenti bisognerà fare una patch al modulo.
E' molto che ti capita questo errore?

**Comment by vivi202** [comment]
no l'ho scaricato ieri il plugin.

**Comment by vivi202** [comment]
ho riprovato stamattina è non va lo stesso.
_________________________________________________________________________________
07-12 13:33:08 ERROR [edia._base.providers.base] Failed getting release from CorsaroNero: Traceback (most recent call last):
  File "/var/www/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/var/www/CouchPotatoServer/couchpotato/core/plugins/base.py", line 198, in urlopen
    raise Exception('Disabled calls to %s for 15 minutes because so many failed requests' % host)
Exception: Disabled calls to itorrents.org for 15 minutes because so many failed requests
_________________________________________________________________________________è dopo un po mi blocca e da questo errore.

**Comment by neothematrix** [comment]
ciao, puoi provare l'ultima versione che ho appena committato? non ho ancora fatto la release quindi dovresti scaricarla direttamente da: https://github.com/bateman/corsaronero-cp-provider/archive/master.zip
appena mi dai feedback faccio la release nuova, grazie mille!

**Comment by vivi202** [comment]
Salve purtroppo non posso testare la nuova release perché sono all'estero per due settimane e non ho il PC.

Il 29 lug 2018 19:37, Gabriele <notifications@github.com> ha scritto:

ciao, puoi provare l'ultima versione che ho appena committato? non ho ancora fatto la release quindi dovresti scaricarla direttamente da: https://github.com/bateman/corsaronero-cp-provider/archive/master.zip<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbateman%2Fcorsaronero-cp-provider%2Farchive%2Fmaster.zip&data=02%7C01%7C%7Cfa1cc74f7f6a4d5cfc6708d5f5824dbe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636684862345611458&sdata=s%2BWYIGbcss9Ro9b%2BUifCgJslaD6xBd5QRyMjaNTVADg%3D&reserved=0>
appena mi dai feedback faccio la release nuova, grazie mille!

**Comment by fabio166** [comment]
Ciao,

Ho installato questa versione e non ho quel problema, tuttavia da qualche mese né la versione precedente né questa arriva a scaricare qualcosa. In debug mode ottengo sempre:

[hpotato.core.plugins.base] Getting cache a313fafa2a061b45dedf0e92777c08dc
[core.media.movie.searcher] Nothing found for ...

Non so se dipende da modifiche a couchpotato o dal plugin. Sto usando l'ultima versione di couchpotato (31/03/2018).

Se riesci a darmi indicazioni sarebbe gradito.

Grazie mille
