### ISSUE TITLE
Addon installato ma non funzionante

### ISSUE THREAD

**Issue by Jorman** [bateman/corsaronero-cp-provider#6]
Ciao, premetto che ho installato il pacchetto su un nas qnap, ho cmq trovato la cartella per l'installazione e da CP vedo e posso configurare l'estensione.

Detto questo, provo a fare eseguire la ricerca a CP di un film che so essere presente su ilcorsaronero, nel log vedo traccia di connessione a ilcorsaronero, ma poi il log restituisce
[iders.torrent.corsaronero] Hit right category: DVDrip is a movie, keep going.
Sicuramente ho sbagliato a configurare qualcosa, oppure può dipendere dal fatto che gira sul nas?

Come posso fare per fare una sorta di debug?

Grazie, J

**Comment by isadic** [comment]
Salve, commento la issue perché mi si è appena presentata, purtroppo. 

Riporto, di seguito il log:

04-17 20:59:41INFO[hpotato.core.plugins.base] Opening url: get http://ilcorsaronero.info/tor/83918/Chernobyl_Diaries_La_Mutazione_2012_iTA_eNG_AC3_BrRip_1080p_x264_TrTd_TeaM, data: []

04-17 20:59:41INFO[ronero-cp-provider-master] Hit right category: DVDrip is a movie, keep going.


La versione è la: 965b8089f1d8b58f4201618d0dbd15a77900d003 (‎22‎/‎02‎/‎2015‎ ‎17‎:‎07‎:‎43).

**Comment by neothematrix** [comment]
Perdonami, quale sarebbe il problema qui? Dal tuo log non si capisce, quel messaggio non è un errore è normale, ti puoi spiegare meglio? Se vuoi mettere il log completo, ti chiederei di usare pastebin e incollare il link qua invece di incollare tutto il testo completo nel post.

**Comment by isadic** [comment]
Ti ringrazio per la risposta tempestiva.
Il problema è che, se non ho capito male, la release viene identificata come DVD-Rip, pur essendoci 1080p nel titolo ed essendo più grande di quanto specificato nella categoria.

Ecco il log completo, ripulito:
http://pastebin.com/77wBZ1AH

**Comment by neothematrix** [comment]
ciao, ti stai facendo confondere da quel messaggio (probabilmente è bene toglierlo), è un messaggio di debug e significa che sul sito del corsaronero, il film appare nella categoria "dvdrip", come puoi vedere tu stesso da questa pagina: http://ilcorsaronero.info/cat/1, significa semplicemente che il film che ha trovato è un film e non un "pc games", "musica" o "app win" che sono le altre categorie di torrent presenti sul corsaronero. NON significa che il plugin ha riconosciuto la release come dvdrip, quel messaggio lo avrai sempre. Tutto appare normale nel tuo log, ignora tranquillamente quel messaggio.
Piuttosto, qual'è il problema reale?

**Comment by isadic** [comment]
Il problema è che queste release vengono ignorate totalmente. Succede anche sull'addon tntvillage, ma credo sia OT, pur essendo un fork di questo addon.

**Comment by neothematrix** [comment]
ok ma possono esserci mille motivi (il piu delle volte è perchè non viene riconosciuto correttamente il nome) per cui vengono ignorate, nel log viene scritto tutto, ma devi impostare il log in debug. Fai una cosa, cambia il log in debug (lo fai nel menu settings di couchpotato, flaggando la casella "show advanced settings" e poi dal tab "General", flagghi la casella "Debug"), forza la ricerca del film nuovamente, e incolla il log completo, dal momento che inizia la ricerca al momento in cui finisce dicendo che non ha trovato release, solo così è possibile verificare come mai vengono scartate le release e se è un problema del plugin.

**Comment by isadic** [comment]
http://pastebin.com/e4epW7CL

Grazie per il supporto.

**Comment by neothematrix** [comment]
ciao,
ti confermo che hai trovato un bel bug! Ho indagato un po meglio, e CouchPotato quando cerca tra i vari tag per determinare la qualità, prende il titolo della release e cerca tutte le parole *separate da simboli che "non sono caratteri"*, per come viengono pero' gestiti i torrent di corsaronero pero', invece degli spazi o dei puntini, come separatori, ci sono gli "_" che sono considerati ahime, caratteri, quindi couchpotato non trovava nessun tag nel nome del file, nonostante ci fosse!
Ho già corretto il bug in una versione locale del plugin, tra poco faccio il commit!

**Comment by neothematrix** [comment]
ciao,
tutto fatto, fammi sapere se ora va bene!

**Comment by isadic** [comment]
Perdonami per la risposta in ritardo, ora dal log sembra che legga i tag in maniera ottimale, ma non capisco come mai finisce per un nulla di fatto, prendendo un 1080p per un BRRip. Se puoi dare uno sguardo al log te lo posto:
http://pastebin.com/mJJPESCv

**Comment by neothematrix** [comment]
ciao,
sembra che il torrent sia troppo piccolo per essere un 1080p, come sono configurati i limiti di dimensione su couchpotato?
Il torrent è 1474.56 MB e quando lo va a confrontare coi limiti impostati su couchpotato non trova 1080p:

```
Found brrip via release size: 700.0 MB < 1474.56 MB < 7000.0 MB
Found dvdrip via release size: 600.0 MB < 1474.56 MB < 2400.0 MB
Found scr via release size: 600.0 MB < 1474.56 MB < 1600.0 MB
```

A giudicare dagli altri log, sembra che il range di dimensione per essere riconosciuto come 1080p sia
maggiore di 4000.0 MB e inferiore a 20000.0 MB
In questo caso, se vuoi accettare 1080p da 1500MB dovrai modificare questi parametri su couchpotato, abbassando il limite inferiore, attualmente impostato a 4000, sotto la dimensione del torrent, che in questo caso è 1474.
Ma come ho detto all'altro ragazzo, sta a te decidere se sia giusto accettare un 1080p da 1.5GB (che a me sembra piuttosto piccolo come dimensione), a te la scelta

**Comment by isadic** [comment]
Sul 1080p hai ragione, e perdonami se sono leggermente OT, in quanto parliamo di CP e non dell'addon specificatamente. Volevo solo chiederti se è normale che, avendo preso in considerazione sia i 720p che i 1080p, un 720p da 5GB venga ignorato.

**Comment by neothematrix** [comment]
ciao,
allora se parli della release:
```
Chernobyl.Diaries.BDrip720p.H264.Eng.Ita.Ac3.Sub.Eng.Ita.
```
viene effetivamente correttamente riconosciuta come 720p, ma poi da un altro errore:
```
Wrong: Chernobyl.Diaries.BDrip720p.H264.Eng.Ita.Ac3.Sub.Eng.Ita., undetermined naming. Looking for 'Chernobyl Diaries (2012)'
```
come vedi, il titolo della release non contiene l'anno, se l'avesse contenuto, quella release sarebbe stata accettata. Alternativamente, puoi abilitare l'opzione recentemente introdotta, di ignorare l'anno, lo fai dalle impostazioni del plugin corsaronero.
